# Generated by Django 5.0 on 2024-01-26 18:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='group_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subject_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('fullname', models.CharField(max_length=150)),
                ('job', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=100)),
                ('head_text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='schedule_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.group_model')),
            ],
            options={
                'ordering': ['date', 'group'],
            },
        ),
        migrations.CreateModel(
            name='schedule_subject_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.schedule_model')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.subject_model')),
            ],
        ),
        migrations.AddField(
            model_name='schedule_model',
            name='subjects',
            field=models.ManyToManyField(through='university.schedule_subject_model', to='university.subject_model'),
        ),
    ]
