# Generated by Django 5.0 on 2024-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_student_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='user',
        ),
    ]
